[shell]
program = "/usr/bin/zsh"
args = []

[font]
normal.family = "FiraCode Nerd Font Mono"
normal.style = "Regular"
bold.family = "FiraCode Nerd Font Mono"
bold.style = "Bold"
italic.family = "FiraCode Nerd Font Mono"
italic.style = "Italic"
size = 14.0

[window]
padding.x = 8
padding.y = 8
dynamic_title = true
decorations = "full"

[colors.primary]
background = "#1a1b26"
foreground = "#c0caf5"

[colors.normal]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[scrolling]
history = 10000
multiplier = 3

[env]
COLORTERM = "truecolor"
